name: ignition_mobile
description: Ignition Mobile — a Flutter mobile application for the Ignition Pay ecosystem.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  stellar_address_kit:
    path: ../packages/core-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
