name: stellar_address_kit
description: A robust Dart implementation of the Stellar Address Kit, providing safe handling of G, M, and C addresses with cross-language specification compliance.
version: 1.0.1
repository: https://github.com/Boxkit-Labs/stellar-address-kit/tree/main/packages/core-dart
homepage: https://stellar.org
documentation: https://github.com/Boxkit-Labs/stellar-address-kit/tree/main/docs
issue_tracker: https://github.com/Boxkit-Labs/stellar-address-kit/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
