name: Publish to pub.dev

on:
  push:
    tags:
      - 'core-dart/v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: cd packages/core-dart && dart pub get
      - name: Publish to pub.dev
        run: cd packages/core-dart && dart pub publish --force
